// eslint-disable-next-line no-sparse-arrays
export let jsonCafe = [
  // ---------------Drinks
  {
    name: "GOLDEN ALE",
    detail:
      " 4.86% - IBU 14 |      Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "HONEY",
    detail:
      "5.64% - IBU 22 |      Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "REDIPAN",
    detail:
      "5.7% - IBU 40 |       Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31   Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "ROJA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  },
  {
    name: "IPA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  }, 
   {
    name: "GOLDEN ALE",
    detail: "4.86% - IBU 14 | Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "LATAS",
  },
  {
    name: "GERMAN PILS",
    detail: "5.2% - IBU 22 | Una cerveza alemana amarga, de cuerpo ligero, altamente atenuada, de color dorado y fermentacion baja, que exhibe una excelente retencion de espuma y un elegante aroma a lupulo floral. Chispeante, limpia y refrescante, una Pilsner que exhibe la mas fina calidad de malta y lupulo Alemán.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31  |    Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SCOTTISH EXPORT",
    detail: "5.51% - IBU 18 |   Cerveza maltosa, con notas acarameladas y algo de butterscotch. De color cobrizo, con espuma blanquecina y cremosa. Sabor a migas de pan tostado, bizcochos y galletas. Amargor bajo y cuerpo medio, carbonatación moderada.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "BELGIAN DUBBEL",
    detail: "7.48%  - IBU 22.9 |  Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "POKER BOURBON",
    detail: "8.53%  - IBU 51  |   Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "PORTER",
    detail: "5.7% - IBU 26.6 |    Cerveza oscura profunda con un rojo intenso a trasluz. Caracter tostado y notas a chocolate. Sabores a malta, bizcochos y pan tostado. Cuerpo medio alto, amargor medio con notas terrosas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "TIRADA",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "PORRÓN",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "FERNET BRANCA",
    detail: "",
    price: "900",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "MINT TONIC",
    detail: "Branca menta + Tónica",
    price: "800",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA +NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA + SPEED",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "APEROL SPRITZ",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "PRPEE WHISKY",
    detail: "Whisky Jameson, manzana macerada, almíbar y dash de limon",
    price: "110",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + TONICA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "NEGRONI",
    detail: "",
    price: "1100",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "HOLDMOSER + SPEED",
    detail: "",
    price: "1500",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "JAGGER + SPEED",
    detail: "",
    price: "1700",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "BEEFEATER",
    detail: "",
    price: "1200",
    section: "ONLY GIN",
  },
  {
    name: "BOMBAY",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "BULL DOG",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "MERLE",
    detail: "",
    price: "1000",
    section: "ONLY GIN",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "LIMA & MENTA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMA & MENTA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PEPINO Y ROMERO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PEPINO Y ROMERO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ROMERO Y POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ROMERO Y POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
 
  {
    name: "TIRADO",
    detail: "",
    price: "800",
    section: "PORTELA",
  },
  {
    name: "PALERMO TONIC",
    detail: "gin tirado, lima, pomelo, jugo de limón, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "BERRIES TONIC",
    detail: "gin tirado, lima, frutos rojos, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "RECOLETA TONIC",
    detail: "gin tirado, lima, maracuya, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "JULEP TONIC",
    detail: "refrescante julep de gin con jugo de pomelo",
    price: "1100",
    section: "BAIRES",
  },
  {
    name: "TOM COLLINS",
    detail: "gin tirado, almíbar, jugo de limón y soda",
    price: "",
    section: "BAIRES",
  },
  {
    name: "BERRIES",
    detail: "sernova - frutos rojos - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PASSION FRUIT",
    detail: "sernova - maracuya - dash almíbar - jugo de naranja",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PEACH",
    detail: "sernova - durazno natural - soda - almíbar - jugo de limón",
    price: "900",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PUNCH ESTACION",
    detail: "ron dorado - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "PUNCH MALIBU",
    detail: "ron malibu - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "MAITE",
    detail: "ron blanco - ron malibu - anana macerado - jugo naranja",
    price: "1100",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO TRADICIONAL",
    detail: "ron blanco - menta - limón - almibar - soda",
    price: "900",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO MARACUYA",
    detail: "ron blanco - maracuya - menta - limón - azúcar - soda",
    price: "950",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRISIMA",
    detail: "Ron blanco- lima - azúcar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRINHA",
    detail: "Cachaza, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIROSKA",
    detail: "Vodka, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "BOOM",
    detail: "shaken de ron blanco con lima y azúcar",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI FRUTOS ROJOS",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI MARACUYA",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI DURAZNO",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGER JULEP",
    detail: "jagger - menta - azúcar negra - dash limón - jugo de naranja o pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGERBULL",
    detail: "jagger + red bull",
    price: "1800",
    section: "COKTELEÍA",
  },
  {
    name: "APPLELIME JAGGER",
    detail: "jagger - manzana - lima macerados - jugo de manzana",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA BREZZE",
    detail: "absolut vainilla - arándanos - jugo de pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT MANDARIN REBEL",
    detail: "absolut mandarina - coca cola - rodaja de naranja",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT P.S",
    detail: "absolut pears - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA COLA",
    detail: "absolut vainilla - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT APEACH TONIC",
    detail: "absolut apeach - tónica - lima",
    price: "1300",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "ABSOLUT MANGO MOJITO",
    detail: "absolut mango - menta - limón - azúcar - soda",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + SPEED",
    detail: "",
    price: "1600",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + RED BULL",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "COCA~COLA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SPRITE",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "FANTA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SCHWEPPES POMELO",
    detail: "500cc",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA CON GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA SIN GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AQUARIUS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA CLASICA",
    detail: "menta - limón - azúcar - agua",
    price: "500",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE MARACUYA",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE FRUTOS ROJOS",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA SHAKEN",
    detail: "shaken de jugo de naranja, pulpa de maracuya, almibar y jugo de naranja",
    price: "650",
    section: "COKTELEÍA",
  },
  {
    name: "MIX DE CITRICOS CON FRUTOS ROJOS",
    detail: "",
    price: "700",
    section: "COKTELEÍA",
  },
  {
    name: "BARON B EXTRA BRUT",
    detail: "750cc",
    price: "6500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON BRUT NATURE",
    detail: "750cc",
    price: "4500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },



  // ---------------Food
  {
    name: "Chicken Fingers",
    detail: "Bastoncitos de pollo con salsa picante",
    price: "1790",
    section: "TAPEOS",
  },
  {
    name: "Cheese Snack",
    detail: "Bastoncitos de muzzarella con sala alioli",
    price: "1700",
    section: "TAPEOS",
  },
  {
    name: "Empanadas veganas",
    detail: "(4) Empanaditas de verduras salteadas, zanahoria, morron, cebolla, berenjena & champigniones.",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "Empanaditas de carne",
    detail: "(4) Empanaditas de carne, cebolla & queso, con salsa picante",
    price: "1700",
    section: "TAPEOS",
  },
  {
    name: "Empanaditas de Pollo",
    detail: "(4) Empanaditas de pollo con salsa aleoli",
    price: "1700",
    section: "TAPEOS",
  },
  {
    name: "Rabas",
    detail: "Rabas con limon & dip salsa aleoli",
    price: "2500",
    section: "TAPEOS",
  },
  {
    name: "Tortilla veggie",
    detail: "Tortilla con jamon, queso, verdeo y lactonesa de ajo",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "Tortilla",
    detail: "Tortilla con roquefort, nuez, verdeo y lactosa de ajo",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "Baires",
    detail: "Papas bañadas con chedar, acompañadas de panceta y verdeo",
    price: "1600",
    section: "PAPAS",
  },
  {
    name: "Palermo",
    detail: "Papas con salchichas, huevo frito y barbacoa casera",
    price: "1700",
    section: "PAPAS",
  },
  {
    name: "Puerto Madero",
    detail: "Papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1700",
    section: "PAPAS",
  },
  {
    name: "Congreso",
    detail: "Papas con bondiola desmenuzada, salsa de queso fundido y pimientos asados",
    price: "1800",
    section: "PAPAS",
  },
  {
    name: "Lomo",
    detail: "Lomo con papas españolas y verduras asadas, con manteca de hierbas. Dip de criolla o chimichurri",
    price: "2400",
    section: "PRINCIPALES",
  },
  {
    name: "Bondiola Braseada",
    detail: "Bondiola braseada cubierta de queso fundido, lonjas de panceta, huevo frito, cebollas caramelizadas y pimientos asados acompañadas de papas españolas",
    price: "2400",
    section: "PRINCIPALES",
  },
  {
    name: "Milanesa Madero",
    detail: "milanesa con fondeau de queso y mix de hongos",
    price: "2300",
    section: "PRINCIPALES",
  },
  {
    name: "Milanesa napo",
    detail: "Milanesa napolitana (salsa de tomate, jamon, queso y oregano) acompañada de papas fritas",
    price: "2200",
    section: "PRINCIPALES",
  },
  {
    name: "Milanesa a Caballo",
    detail: "Milanesa con queso chedar y huevo frito acompañada de papas fritas",
    price: "2300",
    section: "PRINCIPALES",
  },
  {
    name: "Wok de Lomo",
    detail: "Fideos de arroz, verduras salteadas, lomo, panceta, hongos, salsa de soja y semilla de sesamo",
    price: "2600",
    section: "PRINCIPALES",
  },
  {
    name: "Wok de Verdura",
    detail: "Fideos de arros, verduras salteadas, almendras tostadas, salsa de soja y semilla de sesamo.",
    price: "2300",
    section: "PRINCIPALES",
  },
  {
    name: "Wok de Pollo",
    detail: "fideos de arroz, verduras salteadas, pollo, almendras, salsa de soja y semillas de sesamo",
    price: "2300",
    section: "PRINCIPALES",
  },
  {
    name: "Caesar",
    detail: "Mix de hojas verdes, pechuga grille, croutons, queso parmesano y dressing caesar",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "Caprese",
    detail: "Cubos de queso, cherries confitados, aceitunas negras y pesto de albahaca",
    price: "1700",
    section: "ENSALADAS",
  },
  {
    name: "Mediterranea",
    detail: "Mix de hojas verdes, jamon serrano, cheese sticks, tomates cherries y aceite de oliva",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "Crispy",
    detail: "Mix de hojas verdes, pollo grispy, crocantes de panceta, queso en hebras y dressing ranch",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "Baires",
    detail: "Pan de papa, medallon de carne, panceta & doble chedar.",
    price: "1650",
    section: "ENTRE PANES",
  },
  {
    name: "Congreso",
    detail: "Pan de papa, doble carne, tomate, lechuga, jamon y queso.",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "Doble Baires",
    detail: "Pan de papa , doble carne, doble cheddar, panceta, cebolla caramelizada & huevo frito",
    price: "2000",
    section: "ENTRE PANES",
  },
  {
    name: "Palermo",
    detail: "Pan de papa, doble carne, doble chedar, lechuga, cebolla crispy & panceta",
    price: "2000",
    section: "ENTRE PANES",
  },
  {
    name: "Mega Baires",
    detail: "Pan de papa, triple carne, triple chedar, panceta, cebolla caramelizada & huevo frito",
    price: "2700",
    section: "ENTRE PANES",
  },
  {
    name: "Mila",
    detail: "Mila en pan arabe, jamon, queso, lechuga & tomate",
    price: "1900",
    section: "ENTRE PANES",
  },
  {
    name: "Lomo Baires",
    detail: "Lomo en pan arabe, doble cheddar, panceta & huevo frito",
    price: "2100",
    section: "ENTRE PANES",
  },
  {
    name: "Lomo Madero",
    detail: "Lomo en pan arabe, doble cheddar, palta, tomate & huevo",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "Veggie",
    detail: "Medallon de spinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano & ciguliette",
    price: "1900",
    section: "ENTRE PANES",
  },
  {
    name: "Bondiola Madero",
    detail: "Bondiola desmenuzada con salsa criolla, queso tibo, palta, tomate & huevo",
    price: "2000",
    section: "ENTRE PANES",
  },
  {
    name: "Clasica",
    detail: "Mozzarella & Jamon",
    price: "1800",
    section: "PIZZAS",
  },
  {
    name: "Napolitana",
    detail: "Mozzarella - Albahaca & Aceite de oliva.",
    price: "1900",
    section: "PIZZAS",
  },
  {
    name: "Caprese",
    detail: "Mozzarella - Mix de tomates & Pesto de albahaca",
    price: "1850",
    section: "PIZZAS",
  },
  {
    name: "Fuggazza",
    detail: "Mozzarella - Cebolla",
    price: "1950",
    section: "PIZZAS",
  },
  {
    name: "Especial",
    detail: "Mozzarella - Jamon - Morrones - Aceitunas",
    price: "1950",
    section: "PIZZAS",
  },
  {
    name: "Serrana",
    detail: "Mozzarella - Jamon crudo - Rucula",
    price: "2000",
    section: "PIZZAS",
  },
  {
    name: "Americana",
    detail: "Mozzarella - Panceta - Huevos Fritos",
    price: "1950",
    section: "PIZZAS",
  },
  {
    name: "4 Quesos",
    detail: "",
    price: "2300",
    section: "PIZZAS",
  },
  {
    name: "Baires Pizza",
    detail: "Mozzarella - Panceta - Huevos Fritos",
    price: "1950",
    section: "PIZZAS",
  },
  {
    name: "Pizza Individual",
    detail: "",
    price: "1500",
    section: "SIN T.A.C.C",
  },
  {
    name: "Panini",
    detail: "Jamon & Queso",
    price: "1500",
    section: "SIN T.A.C.C",
  },
  {
    name: "Papas",
    detail: "Papas con cheddar - Panceta & Verdeo.",
    price: "1600",
    section: "SIN T.A.C.C",
  },
  {
    name: "Empanadas veganas",
    detail: "4 Empanadas de verduras salteadas, zanahoria, morron, cebolla, berenjena & champigniones",
    price: "1600",
    section: "VEGGIE",
  },
  {
    name: "Papas Puerto Madero",
    detail: "Papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1700",
    section: "VEGGIE",
  },
  {
    name: "Wok de Verdura",
    detail: "Fideos de arros, verduras salteadas, almendras tostadas, salsa de soja y semilla de sesamo",
    price: "2300",
    section: "VEGGIE",
  },
  {
    name: "Buerger Veggie",
    detail: "medallon de espinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano y ciboulette",
    price: "1600",
    section: "VEGGIE",
  },

  // ---------------Wines
  {
    name: "Canilla 1",
    detail: "malbec reserva (mendoza)",
    price: "350",
    section: "VINO TIRADO",
  },
  {
    name: "Canilla 2",
    detail: "malbec premium (mendoza)",
    price: "400",
    section: "VINO TIRADO",
  },
  {
    name: "Canilla 3",
    detail: "cabernet franc premium (mendoza)",
    price: "400",
    section: "VINO TIRADO",
  },
  {
    name: "Canilla 4",
    detail: "blend de malbec/malbec de diferentes alturas (mendoza)",
    price: "350",
    section: "VINO TIRADO",
  },
  {
    name: "NUBE NEGRA",
    detail: "",
    price: "3500",
    section: "MALBEC",
  },
  {
    name: "TERRAZAS DE LOS ANDES APELACIÓN DE ORIGEN",
    detail: "",
    price: "2500",
    section: "MALBEC",
  },
  {
    name: "GRAN VINO CHAÑARMUYO",
    detail: "",
    price: "1800",
    section: "MALBEC",
  },
  {
    name: "EDUARDO VIDAL ",
    detail: "el espía cap.1",
    price: "1800",
    section: "MALBEC",
  },
  {
    name: "MALABARISTA",
    detail: "",
    price: "1500",
    section: "MALBEC",
  },
  {
    name: "CAUTIVADOR",
    detail: "",
    price: "1500",
    section: "MALBEC",
  },
  {
    name: "TUCUMEN RESERVA",
    detail: "",
    price: "1400",
    section: "MALBEC",
  },
  {
    name: "TESTA MATTA",
    detail: "",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "EDUARDO VIDAL",
    detail: "cayado",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "GUASON",
    detail: "",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "TERRAZAS DE LOS ANDES RESERVA",
    detail: "",
    price: "1200",
    section: "CABERNET SAUVIGNON",
  },
  {
    name: "GRAN VINO CHAÑARMUYO FRANC",
    detail: "",
    price: "1800",
    section: "CABERNET FRANC",
  },
  {
    name: "GUASON FRANC",
    detail: "",
    price: "1200",
    section: "CABERNET FRANC",
  },
  {
    name: "DON BICHO REVERA WINES",
    detail: "",
    price: "2500",
    section: "ORGÁNICOS",
  },
  {
    name: "GRAN VINO CHAÑARMUYO TANAT",
    detail: "",
    price: "1800",
    section: "TANAT",
  },
  {
    name: "MALABARISTA COFERMENTADO N1",
    detail: "",
    price: "1900",
    section: "BLEND/CO-FERMENTADOS/BI-VARIETALES",
  },
  {
    name: "MALABARISTA COFERMENTADO N2",
    detail: "",
    price: "1900",
    section: "BLEND/CO-FERMENTADOS/BI-VARIETALES",
  },
  {
    name: "TURBIO CRUZA DE BLANCAS",
    detail: "clasico",
    price: "1900",
    section: "VINO BLANCO",
  },
  {
    name: "MALABARISTA ESPUMANTE DULCE",
    detail: "",
    price: "1300",
    section: "VINO BLANCO",
  },

  {
    name: "FINCA GABRIEL DULCE",
    detail: "",
    price: "1200",
    section: "VINO BLANCO",
  },

  {
    name: "GUASON ESPUMANTE DULCE",
    detail: "",
    price: "1200",
    section: "VINO BLANCO",
  },
  {
    name: "SIEMPRE TENGO UN PLAN B",
    detail: "torrontes dulce",
    price: "1600",
    section: "VINO BLANCO",
  },
  {
    name: "TERRAZAS DE LOS ANDES RESERVA ROSE DE MALBECS",
    detail: "",
    price: "1600",
    section: "VINO ROSADO",
  },
  {
    name: "FINCA GABRIEL ROSE DULCE",
    detail: "",
    price: "1200",
    section: "VINO ROSADO",
  }
  
]
// ----------------------------FIN---------