// eslint-disable-next-line no-sparse-arrays
export let jsonCafe = [
  // ---------------Drinks
  {
    name: "GOLDEN ALE",
    detail:
      " 4.86% - IBU 14 |      Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "HONEY",
    detail:
      "5.64% - IBU 22 |      Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "",
    detail: "",
    price: "",
    section: "BIRRITAS",
  },
  {
    name: "REDIPAN",
    detail:
      "5.7% - IBU 40 |       Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31   Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "ROJA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  },
  {
    name: "IPA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  }, 
   {
    name: "GOLDEN ALE",
    detail: "4.86% - IBU 14 | Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "LATAS",
  },
  {
    name: "GERMAN PILS",
    detail: "5.2% - IBU 22 | Una cerveza alemana amarga, de cuerpo ligero, altamente atenuada, de color dorado y fermentacion baja, que exhibe una excelente retencion de espuma y un elegante aroma a lupulo floral. Chispeante, limpia y refrescante, una Pilsner que exhibe la mas fina calidad de malta y lupulo Alemán.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31  |    Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SCOTTISH EXPORT",
    detail: "5.51% - IBU 18 |   Cerveza maltosa, con notas acarameladas y algo de butterscotch. De color cobrizo, con espuma blanquecina y cremosa. Sabor a migas de pan tostado, bizcochos y galletas. Amargor bajo y cuerpo medio, carbonatación moderada.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "BELGIAN DUBBEL",
    detail: "7.48%  - IBU 22.9 |  Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "POKER BOURBON",
    detail: "8.53%  - IBU 51  |   Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "PORTER",
    detail: "5.7% - IBU 26.6 |    Cerveza oscura profunda con un rojo intenso a trasluz. Caracter tostado y notas a chocolate. Sabores a malta, bizcochos y pan tostado. Cuerpo medio alto, amargor medio con notas terrosas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "TIRADA",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "PORRÓN",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "FERNET BRANCA",
    detail: "",
    price: "900",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "MINT TONIC",
    detail: "Branca menta + Tónica",
    price: "800",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA +NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA + SPEED",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "APEROL SPRITZ",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "PRPEE WHISKY",
    detail: "Whisky Jameson, manzana macerada, almíbar y dash de limon",
    price: "110",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + TONICA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "NEGRONI",
    detail: "",
    price: "1100",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "HOLDMOSER + SPEED",
    detail: "",
    price: "1500",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "JAGGER + SPEED",
    detail: "",
    price: "1700",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "BEEFEATER",
    detail: "",
    price: "1200",
    section: "ONLY GIN",
  },
  {
    name: "BOMBAY",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "BULL DOG",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "MERLE",
    detail: "",
    price: "1000",
    section: "ONLY GIN",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "LIMA & MENTA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMA & MENTA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PEPINO Y ROMERO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PEPINO Y ROMERO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ROMERO Y POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ROMERO Y POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
 
  {
    name: "TIRADO",
    detail: "",
    price: "800",
    section: "PORTELA",
  },
  {
    name: "PALERMO TONIC",
    detail: "gin tirado, lima, pomelo, jugo de limón, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "BERRIES TONIC",
    detail: "gin tirado, lima, frutos rojos, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "RECOLETA TONIC",
    detail: "gin tirado, lima, maracuya, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "JULEP TONIC",
    detail: "refrescante julep de gin con jugo de pomelo",
    price: "1100",
    section: "BAIRES",
  },
  {
    name: "TOM COLLINS",
    detail: "gin tirado, almíbar, jugo de limón y soda",
    price: "",
    section: "BAIRES",
  },
  {
    name: "BERRIES",
    detail: "sernova - frutos rojos - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PASSION FRUIT",
    detail: "sernova - maracuya - dash almíbar - jugo de naranja",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PEACH",
    detail: "sernova - durazno natural - soda - almíbar - jugo de limón",
    price: "900",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PUNCH ESTACION",
    detail: "ron dorado - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "PUNCH MALIBU",
    detail: "ron malibu - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "MAITE",
    detail: "ron blanco - ron malibu - anana macerado - jugo naranja",
    price: "1100",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO TRADICIONAL",
    detail: "ron blanco - menta - limón - almibar - soda",
    price: "900",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO MARACUYA",
    detail: "ron blanco - maracuya - menta - limón - azúcar - soda",
    price: "950",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRISIMA",
    detail: "Ron blanco- lima - azúcar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRINHA",
    detail: "Cachaza, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIROSKA",
    detail: "Vodka, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "BOOM",
    detail: "shaken de ron blanco con lima y azúcar",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI FRUTOS ROJOS",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI MARACUYA",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI DURAZNO",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGER JULEP",
    detail: "jagger - menta - azúcar negra - dash limón - jugo de naranja o pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGERBULL",
    detail: "jagger + red bull",
    price: "1800",
    section: "COKTELEÍA",
  },
  {
    name: "APPLELIME JAGGER",
    detail: "jagger - manzana - lima macerados - jugo de manzana",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA BREZZE",
    detail: "absolut vainilla - arándanos - jugo de pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT MANDARIN REBEL",
    detail: "absolut mandarina - coca cola - rodaja de naranja",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT P.S",
    detail: "absolut pears - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA COLA",
    detail: "absolut vainilla - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT APEACH TONIC",
    detail: "absolut apeach - tónica - lima",
    price: "1300",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "ABSOLUT MANGO MOJITO",
    detail: "absolut mango - menta - limón - azúcar - soda",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + SPEED",
    detail: "",
    price: "1600",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + RED BULL",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "COCA~COLA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SPRITE",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "FANTA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SCHWEPPES POMELO",
    detail: "500cc",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA CON GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA SIN GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AQUARIUS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA CLASICA",
    detail: "menta - limón - azúcar - agua",
    price: "500",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE MARACUYA",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE FRUTOS ROJOS",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA SHAKEN",
    detail: "shaken de jugo de naranja, pulpa de maracuya, almibar y jugo de naranja",
    price: "650",
    section: "COKTELEÍA",
  },
  {
    name: "MIX DE CITRICOS CON FRUTOS ROJOS",
    detail: "",
    price: "700",
    section: "COKTELEÍA",
  },
  {
    name: "BARON B EXTRA BRUT",
    detail: "750cc",
    price: "6500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON BRUT NATURE",
    detail: "750cc",
    price: "4500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },



  // ---------------Food
  {
    name: "CHICKEN FINGERS",
    detail: "bastoncitos de pollo con salsa picante   ------------ SALSAS ALIOLI | PICANTE | CRIOLLA | CHEDDAR",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "CHEESE SNACKS",
    detail: "bastoncitos de muzzarella con salsa alioli",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADAS VEGANAS",
    detail: "4 empanadas de verduras salteadas, zanahoria, morron, cebolla, berenjenas y champigniones",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADAS DE CARNE",
    detail: "4 empanadas de carne, cebolla y queso con salsa picante",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADS DE POLLO",
    detail: "4 empanadas de pollo con salsa alioli",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "RABAS",
    detail: "rabas con limon y dip salsa alioli",
    price: "2500",
    section: "TAPEOS",
  },
  {
    name: "TORTILLA",
    detail: "tortilla con jamón, queso, verdeo y lactonesa de ajo",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "TIRTUKKA VEGGIE",
    detail: "tortilla con roquefort, nuez, verdeo y lactonesa de ajo",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "BAIRES",
    detail: "papas bañadas con cheddar, acompañadas de panceta y verdeo",
    price: "1400",
    section: "PAPAS",
  },
  {
    name: "PALERMO",
    detail: "papas con salchichas, huevo frito y barbacoa",
    price: "1500",
    section: "PAPAS",
  },
  {
    name: "PUERTO MADERO",
    detail: "papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1600",
    section: "PAPAS",
  },
  {
    name: "CONGRESO",
    detail: "papas con bondiola desmenuzada, salsa de queso fundido y pimientos asados",
    price: "1700",
    section: "PAPAS",
  },
  {
    name: "LOMO ACOMPAÑADO DE PAPAS ESPAÑOLAS",
    detail: "lom con papas españolas verduras asadas, con manteca de hirbas. dip de criolla con chimichurri",
    price: "2100",
    section: "PRINCIPALES",
  },
  {
    name: "BONDIOLA ACOMPAÑADA DE PAPAS ESPAÑOLAS",
    detail: "bondiola braseada cubierta de queso fundido, lonjas de panceta, huevos fritos, cebolla caramelizada y pimientos asados acompañadas de papas españolas",
    price: "2100",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA MADERO",
    detail: "milanesa con fondeau de queso y mix de hongos",
    price: "1900",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA NAPO",
    detail: "milanesa,salsa de tomate, jamon, queso y oregano - acompañada con papas españolas",
    price: "1700",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA A CABALLO",
    detail: "milanesa con queso cheddar y huevo frito acomáñada con papas fritas",
    price: "1800",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE LOMO",
    detail: "fideos de arroz, verduras salteadas, lomo, panceta, hongos, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE VERDURA",
    detail: "fideos de arroz, verduras salteadas, almendras tostadas, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE POLLO",
    detail: "fideos de arroz, verduras salteadas, pollo, almendras, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "CESAR",
    detail: "mix de hojas verdes, péchuga grille, croutons, queso parmesano y sressing caesar",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "CAPRESSE",
    detail: "cubos de queso, cherrys confitados, aceitunas negras y pesto de almbahaca",
    price: "1700",
    section: "ENSALADAS",
  },
  {
    name: "MEDITERRANEA",
    detail: "mix de hojas verdes, jamon serrano, cheese sticks, tomates cherry, aceite de oliva",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "CRISPY",
    detail: "mix de hojas verdes, pollo crispy, crocantes de panceta, queso en hebras y dressing ranch",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "BAIRES",
    detail: "pan de papa, medallon de carne, panceta y doble cheddar-------------todo incluye papas",
    price: "1500",
    section: "ENTRE PANES",
  },
  {
    name: "CONGRESO",
    detail: "pan de papa, doble carne, doble cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "DOBLE BAIRES",
    detail: "pan de papa, doble carne, doble cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1750",
    section: "ENTRE PANES",
  },
  {
    name: "PALERMO",
    detail: "pan de papa, triple carne, triple cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1750",
    section: "ENTRE PANES",
  },
  {
    name: "MEGA BAIRES",
    detail: "pan de papa. triple carne, triple cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "",
    section: "ENTRE PANES",
  },
  {
    name: "MILA",
    detail: "mila en pan arabe, jamon, queso, lechuga y tomate",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "LOMO BAIRES",
    detail: "lomo en pan arabe, doble cheddar, panceta y huevo frito",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "LOMO MADERO",
    detail: "lomo en pan arabe, doble cheddar, palta, tomate y huevo",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "VEGGIE",
    detail: "medallon de espinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano y ciboulette",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "BONDIOLA MADERO",
    detail: "bondiola desmenuzada con salsa criolla, queso tibo, palta, tomate y huevo",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "CLÁSICA",
    detail: "muzzarella y jamon",
    price: "1300",
    section: "PIZZAS",
  },
  {
    name: "NAPOLITANA",
    detail: "muzzarella, albahaca y aceite de oliva",
    price: "1550",
    section: "PIZZAS",
  },
  {
    name: "ESPECIAL",
    detail: "muzzarella, jamon, morrones y aceitunas",
    price: "1650",
    section: "PIZZAS",
  },
  {
    name: "SERRANA",
    detail: "muzzarella, jamon crudo y rucula",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "AMERICANA",
    detail: "muzzarella, panceta y huevo frito",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "4 QUESOS",
    detail: "",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "BAIRES",
    detail: "muzzarella, cheddar, pollo, barbacoa casera y verdeo",
    price: "1800",
    section: "PIZZAS",
  },
  {
    name: "PIZZA INDIVIDUAL",
    detail: "",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "PANINI",
    detail: "jamón y queso",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "PAPAS",
    detail: "papas con cheddar, panceta y verdeo",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "EMPANADAS VEGANAS",
    detail: "3 empanadas de verduras salteadas, zanahoria, morron, cebolla, berenjena y champignoines",
    price: "1400",
    section: "VEGGIE",
  },
  {
    name: "PAPAS PUERTO MADERO",
    detail: "papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1600",
    section: "VEGGIE",
  },
  {
    name: "WOK DE VERDURAS",
    detail: "fideos de arroz, verduras salteadas, almendras tostadas, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "VEGGIE",
  },
  {
    name: "BURGUER VEGGIE",
    detail: "medallon de espinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano y ciboulette",
    price: "1600",
    section: "VEGGIE",
  },

  // ---------------Wines
  {
    name: "",
    detail: "",
    price: "",
    section: "ESPUMANTES",
  },
  {
    name: "Espresso",
    detail: "JARRITO",
    price: "500",
    section: "Cafe",
  },
  {
    name: "Espresso mediano",
    detail: "",
    price: "600",
    section: "Cafe",
  },
  ,
  {
    name: "Cafe con leche",
    detail: "",
    price: "750",
    section: "Cafe",
  },

  {
    name: "Frapuchino",

    detail: "",
    price: "950",
    section: "Cafe",
  },
  {
    name: "Capuccino",

    detail: "",
    price: "850",
    section: "Cafe",
  },
  {
    name: "Submarino ",

    detail: "Dosis de leche espumada a 90° con barra de chocolate amargo ",
    price: "850",
    section: "Cafe",
  },
  {
    name: "Té",

    detail: "› Consultar por opciones",
    price: "450",
    section: "Cafe",
  },
  {
    name: "Medialuna",

    detail: "›Dulce o Salada",
    price: "200",
    section: "Desayuno/Merienda",
  },
  {
    name: "Medialuna con jamon y queso",

    detail: "›",
    price: "300",
    section: "Desayuno/Merienda",
  },
  {
    name: "Tostadas x4",

    detail: "› Pan comun o integral - vienen con manteca y mermelada ",
    price: "900",
    section: "Desayuno/Merienda",
  },
  {
    name: "Brusquetas de palta",

    detail: "› Huevo, panceta y queso crema",
    price: "800",
    section: "Desayuno/Merienda",
  },
  {
    name: "Brusqueta capresse",

    detail: "›",
    price: "700",
    section: "Desayuno/Merienda",
  },
  {
    name: "Tostado Primavera",

    detail: "›",
    price: "1600",
    section: "Desayuno/Merienda",
  },

  {
    name: "Tostado jamon y queso",

    detail: "›",
    price: "1300",
    section: "TAPEOS",
  },
  {
    name: "Tostado Primavera",

    detail: "›",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "Yogurt con granola y frutas de estacion",

    detail: "›",
    price: "750",
    section: "Desayuno/Merienda",
  },
  {
    name: "Tarta de coco",

    detail: "› Porcion",
    price: "750",
    section: "DELICATESSEN",
  },
  {
    name: "Torta Cabsha",

    detail: "›Porcion",
    price: "750",
    section: "DELICATESSEN",
  },
  {
    name: "Crumblee de manzana",

    detail: "›Porcion",
    price: "800",
    section: "DELICATESSEN",
  },
  {
    name: "Flan casero",

    detail: "›",
    price: "900",
    section: "POSTRES",
  },
  {
    name: "Bochas de helado",

    detail: "›",
    price: "900",
    section: "POSTRES",
  },
  {
    name: "Frutillas con crema",

    detail: "›",
    price: "1200",
    section: "POSTRES",
  },
  {
    name: "Ensalada de frutas con Helado de americana",

    detail: "›",
    price: "1100",
    section: "POSTRES",
  },
  {
    name: "Chocotorta",

    detail: "›",
    price: "900",
    section: "POSTRES",
  },
  {
    name: "Papas fritas",

    detail: "› ",
    price: "1100",
    section: "TAPEOS",
  },
  {
    name: "Papas gratinadas ",

    detail: "› ",
    price: "1300",
    section: "TAPEOS",
  },
  {
    name: "Langostinos rebozados",

    detail: "›",
    price: "3200",
    section: "TAPEOS",
  },
  {
    name: "Provoleta",

    detail: "› Queso provolone fundido con pesto y tomates cherry",
    price: "1100",
    section: "TAPEOS",
  },

  {
    name: "Tapero para compartir ",
    detail: "› Rabas, Bastoncitos de Muzza, Aros de cebolla, Pollo Crispy",
    price: "5200",
    section: "TAPEOS",
  },
  {
    name: "Rabas",

    detail: "› CON LIMÓN Y ALIOLI",
    price: "3100",
    section: "TAPEOS",
  },
  {
    name: "Bastoncitos de muzzarella",

    detail: "› ",
    price: "2100",
    section: "TAPEOS",
  },
  {
    name: "Tostados",

    detail: "",
    price: "1000",
    section: "TAPEOS",
  },
  {
    name: "Avocado toast",

    detail: "",
    price: "900",
    section: "TAPEOS",
  },
  {
    name: "Aros de cebolla",

    detail: "",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "Pollo crispy",

    detail: "",
    price: "1900",
    section: "TAPEOS",
  },

  {
    name: "Lomito jyq",

    detail: "›sale con fritas o ensalada: mixta",
    price: "2100",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Lomito completo ",

    detail:
      "›sale con fritas o ensalada: mixta - Jamon, queso, lechuga, tomate ",
    price: "2400",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de terneta jyq",

    detail: "›sale con fritas o ensalada: mixta ",
    price: "2000",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de ternera completa ",

    detail: "›sale con fritas o ensalada: mixta ",
    price: "2300",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de ternersa napolitana",

    detail: "›sale con fritas o ensalada: mixta",
    price: "2700",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de pollo jyq",
    //  photo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tyjpNmH6AQFzybK3XbWBX4fkw6E-E4GwJDd7a8SujC1C0xrbhmU3j8n9L8eM31qmAo0&usqp=CAU",
    detail: "›sale con fritas o ensalada: mixta",
    price: "2100",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de pollo completa",
    detail: "›sale con fritas o ensalada: mixta",
    price: "2100",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Milanesa de pollo  napolitana",

    detail: "›sale con fritas o ensalada: mixta",
    price: "2400",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Pechuga grillada a las finas hierbas: ",
    //  photo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tyjpNmH6AQFzybK3XbWBX4fkw6E-E4GwJDd7a8SujC1C0xrbhmU3j8n9L8eM31qmAo0&usqp=CAU",
    detail: "›sale con fritas o ensalada: mixta",
    price: "2300",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Wok de vegetales ",
    //  photo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tyjpNmH6AQFzybK3XbWBX4fkw6E-E4GwJDd7a8SujC1C0xrbhmU3j8n9L8eM31qmAo0&usqp=CAU",
    detail:
      "›Verdeo, Zanahoria, Morron, Berenjena, Zucchini, Repollo, Arroz, Soja y Aceite de Sesamo",
    price: "2100",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Wok de pollo ",
    //  photo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tyjpNmH6AQFzybK3XbWBX4fkw6E-E4GwJDd7a8SujC1C0xrbhmU3j8n9L8eM31qmAo0&usqp=CAU",
    detail:
      "›Ajo, Verdeo, Zanahoria, Morron, Berenjena, Zucchini, Champis, jengibre, Pollo y Salsa Teriyaki",
    price: "2400",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Wok de lomo",
    //  photo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0tyjpNmH6AQFzybK3XbWBX4fkw6E-E4GwJDd7a8SujC1C0xrbhmU3j8n9L8eM31qmAo0&usqp=CAU",
    detail:
      "›Ajo, cebolla Morada, Zanahoria, Morron, Berenjena, Zucchini, Lonjas de Lomo, Soja y Mostaza Dijon",
    price: "2700",
    section: "PLATOS PRINCIPALES",
  },
  {
    name: "Lomito jyq",
    detail: "Sale con fritas o mixtaSale con fritas o mixta",
    price: "2500",
    section: "SANDWICH",
  },
  {
    name: "Lomito completo",
    detail: "sale con fritas o ensalada: mixta - Jamon, queso, lechuga, tomate",
    price: "2800",
    section: "SANDWICH",
  },
  {
    name: "Hamburguesa jyq",
    detail: "Sale con fritas o mixta",
    price: "1900",
    section: "SANDWICH",
  },
  {
    name: "Hamburguesa completa",
    detail: "Sale con fritas o mixta",
    price: "2100",
    section: "SANDWICH",
  },

  {
    name: "Milanesa de ternera jyq",
    detail: "Sale con fritas o mixta",
    price: "2300",
    section: "SANDWICH",
  },
  {
    name: "Milanesa de ternera completa ",
    detail: "Sale con fritas o mixta",
    price: "2700",
    section: "SANDWICH",
  },
  {
    name: "Milanesa de pollo jyq",
    detail: "Sale con fritas o mixta",
    price: "2100",
    section: "SANDWICH",
  },
  {
    name: "Milanesa de pollo completa ",
    detail: "Sale con fritas o mixta",
    price: "2500",
    section: "SANDWICH",
  },
  {
    name: "Hamburguesa veggie en pan de remolacha ",
    detail:
      "Medallon de Lentejas con rucula, tomate y mayo de zanahoria - Sale con fritas o mixta",
    price: "2100",
    section: "SANDWICH",
  },
  {
    name: "Chori a la planchetta ",
    detail:
      "Chori puro cerdo, con jamón, queso, rúcula y chimi. Acompañado con dip de salsa criolla.",
    price: "1800",
    section: "SANDWICH",
  },
  {
    name: "Adicional huevo frito ",
    detail: "",
    price: "600",
    section: "SANDWICH",
  },

  {
    name: "Chori a la plancha ",
    detail:
      "Chori puro cerdo, con jamón, queso, rúcula y chimi. Acompañado con dip de salsa criolla. ",
    price: "1800",
    section: "SANDWICH",
  },
  {
    name: "Vacío tiernizado  ",
    detail: "Con muzarela, tomate, Mayo de albahaca",
    price: "2600",
    section: "SANDWICH",
  },
  {
    name: "Diosa verde",
    detail: "Mix verde, cebolla morada, palta, manzana verde y tomate cherry",
    price: "1600",
    section: "ENSALSADAS",
  },
  {
    name: "Mixta",
    detail: "Lechuga tomate y cebollla",
    price: "1300",
    section: "ENSALSADAS",
  },
  {
    name: "Caesar",
    detail: "Lechuga, pollo, crutones, sardo y salsa caesar",
    price: "2200",
    section: "ENSALSADAS",
  },
  {
    name: "Palta",
    detail: "Arroz, palta, tomate y queso",
    price: "20400",
    section: "ENSALSADAS",
  },
  {
    name: "Fresca",
    detail: "Repollo, Lechuga,Tomate, Zanahoria, Choclo y Hebras de Queso ",
    price: "2200",
    section: "ENSALSADAS",
  },
  {
    name: "SALSA ALIOLI-CAESAR-TARTARA",
    detail:
      "Ideal para acompañar y levantar el sabor de cualquier plato, sandwich o ensalada",
    price: "500",
    section: "DIPS DE SALSAS",
  },
  {
    name: "MAYONESA DE ZANAHORIA-ALBAHACA-CIBOULETTE",
    detail:
      "Ideal para acompañar y levantar el sabor de cualquier plato, sandwich o ensalada",
    price: "500",
    section: "DIPS DE SALSAS",
  },
  {
    name: "MEDITERRANEA Tomate, ajo, verdeo, pepino y limon",
    detail:
      "Tomate, ajo, verdeo, pepino y limon - Ideal para acompañar y levantar el sabor de cualquier plato, sandwich o ensalada",
    price: "500",
    section: "DIPS DE SALSAS",
  },
  {
    name: "Jalapeños Picante",
    detail:
      "Tomate, ajo, verdeo, pepino y limon - Ideal para acompañar y levantar el sabor de cualquier plato, sandwich o ensalada",
    price: "500",
    section: "DIPS DE SALSAS",
  },
  {
    name: "Muzarella",
    detail: "4 porciones",
    price: "1400",
    section: "PIZZAS",
  },
  {
    name: "Americana",
    detail: "Con panceta y huevo - 4 porciones",
    price: "2000",
    section: "PIZZAS",
  },
  {
    name: "Especial",
    detail: "4 porciones",
    price: "1600",
    section: "PIZZAS",
  },
  {
    name: "Napolitana",
    detail: "4 porciones",
    price: "1600",
    section: "PIZZAS",
  },
  {
    name: "Capresse",
    detail: "4 porciones",
    price: "1500",
    section: "PIZZAS",
  },
  {
    name: "4 quesos",
    detail: "Muzza, sardo, roquefort y provolone - 4 porciones",
    price: "1800",
    section: "PIZZAS",
  },
  {
    name: "Roquefort apio y nuez",
    detail: "4 porciones",
    price: "2000",
    section: "PIZZAS",
  },
  {
    name: "Rucula, crudo, sardo y tomates secos",
    detail: "4 porciones",
    price: "2200",
    section: "PIZZAS",
  },
  {
    name: "Agua 500cc ",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "Agua 1,5lts",
    detail: "",
    price: "800",
    section: "SIN ALCOHOL",
  },
  {
    name: "Agua saborizada 500cc",
    detail: "",
    price: "500",
    section: "SIN ALCOHOL",
  },
  {
    name: "Agua saborizada 1,5lts ",
    detail: "",
    price: "1200",
    section: "SIN ALCOHOL",
  },
  {
    name: "Gaseosa 500cc",
    detail: "Linea PEPSI",
    price: "500",
    section: "SIN ALCOHOL",
  },
  {
    name: "Gaseosa 1,5lts",
    detail: "Linea PEPSI",
    price: "1300",
    section: "SIN ALCOHOL",
  },
  {
    name: "Energozante",
    detail: "RED BULL",
    price: "700",
    section: "SIN ALCOHOL",
  },
  {
    name: "Limonada",
    detail: "Con menta y jengibre",
    price: "700",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jarra Limonada",
    detail: "Con menta y jengibre",
    price: "1200",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Pomelada",
    detail: "",
    price: "700",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jarra Pomelada",
    detail: "",
    price: "1200",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jugo de naranja ",
    detail: "Exprimido",
    price: "700",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jarra Jugo de naranja ",
    detail: "Exprimido",
    price: "1200",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jugo Detox ",
    detail: "Manzana verde, apio y pepitn",
    price: "800",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Jugo Beta ",
    detail: "Naranja , pomelo, zanahoria, jengibre",
    price: "800",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Licuado de fruta",
    detail: "",
    price: "700",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "Licuado multifruta",
    detail: "",
    price: "800",
    section: "JUGOS & LICUADOS",
  },
  {
    name: "MIX CITRICO ",
    detail: "Durazno, frutilla, frutos Rojos",
    price: "800",
    section: "SIN ALCOHOL",
  },
  {
    name: "JUGO DETOX",
    detail: "Manzana verde, apio, pepino y Kiwi",
    price: "800",
    section: "SIN ALCOHOL",
  },
  {
    name: "JUGO BETA",
    detail: "Naranja, Pomelo, Zanahoria",
    price: "800",
    section: "SIN ALCOHOL",
  },
  {
    name: "Corona 330",
    detail: "700",
    price: "700",
    section: "CERVEZA",
  },
  {
    name: "Corona 710",
    detail: "",
    price: "1200",
    section: "CERVEZA",
  },
  {
    name: "Stella 330",
    detail: "Lata",
    price: "500",
    section: "CERVEZA",
  },
  {
    name: "Stella 710",
    detail: "",
    price: "1000",
    section: "CERVEZA",
  },
  {
    name: "Lata Patagonia ",
    detail: "",
    price: "700",
    section: "CERVEZA",
  },
  {
    name: "Patagonia 710cc",
    detail: "",
    price: "1200",
    section: "CERVEZA",
  },
  ,
  {
    name: "Malbec Orgánico",
    detail: "Domaine Bousquet",
    price: "2500",
    section: "VINOS & CHAMPAGNE",
  },
  {
    name: "Sauvignon Blanc Orgánico",
    detail: "Domaine Bousquet",
    price: "2200",
    section: "VINOS & CHAMPAGNE",
  },
  {
    name: "Rosé Orgánico",
    detail: "Domaine Bousquet",
    price: "2200",
    section: "VINOS & CHAMPAGNE",
  },
  {
    name: "Extra Brut",
    detail: "Chandon ",
    price: "5200",
    section: "VINOS & CHAMPAGNE",
  },
  {
    name: "Fernet",
    detail: "",
    price: "1200",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Campari",
    detail: "Con Naranja",
    price: "1200",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Vodka con jugo ",
    detail: "Con Naranja",
    price: "1400",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Vermuth ",
    detail: "",
    price: "1000",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "WHISKY JOHNNIE WALKER ",
    detail: "ETIQUETA NEGRA",
    price: "2000",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Cuba libre",
    detail: "",
    price: "1100",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Orange malibu ",
    detail: "",
    price: "1100",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Negroni ",
    detail: "",
    price: "1400",
    section: "COCTELERIA CLASSICA",
  },
  {
    name: "Gin tonic",
    detail: "Bombay",
    price: "1700",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Gin tonic",
    detail: "Bosque",
    price: "1200",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Gin tonic Maracuya",
    detail: "",
    price: "1100",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Gin tonic Frutos rojos",
    detail: "",
    price: "1300",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Jagger julep",
    detail: "",
    price: "1300",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Cynar julep",
    detail: "",
    price: "1400",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Mojito",
    detail: "",
    price: "1100",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Caipirinha ",
    detail: "",
    price: "1300",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Caipiriroska",
    detail: "",
    price: "1400",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Caipirisima",
    detail:
      "Azúcar rubia, Agua, Menta, Limas, Maracuyá, Hielo, Amor                                            ",
    price: "1400",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Caipi de maracuya ",
    detail: "",
    price: "1400",
    section: "COCTELERIA ESPECIAL",
  },
  {
    name: "Daiquiri",
    detail: "",
    price: "1400",
    section: "COCTELERIA CLASSICA",
  },
];
