// eslint-disable-next-line no-sparse-arrays
export let jsonCafe = [
  // ---------------Drinks
  {
    name: "GOLDEN ALE",
    detail:
      " 4.86% - IBU 14 |      Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "HONEY",
    detail:
      "5.64% - IBU 22 |      Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "600",
    section: "BIRRITAS",
  },
  {
    name: "",
    detail: "",
    price: "",
    section: "BIRRITAS",
  },
  {
    name: "REDIPAN",
    detail:
      "5.7% - IBU 40 |       Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31   Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "BIRRITAS",
  },
  {
    name: "ROJA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  },
  {
    name: "IPA ROTATIVA",
    detail: "Consultar.",
    price: "",
    section: "BIRRITAS",
  }, 
   {
    name: "GOLDEN ALE",
    detail: "4.86% - IBU 14 | Cerveza de alta tomabilidad con orientación hacia la malta. Balanceada y limpia. De color amarillo brillante con buena retención de espuma. Suave dulzor de malta y aromas a cereal, con presencia de lúpulo, aunque el amargar es bajo. El final es seco a ligeramente dulce-maltoso",
    price: "600",
    section: "LATAS",
  },
  {
    name: "GERMAN PILS",
    detail: "5.2% - IBU 22 | Una cerveza alemana amarga, de cuerpo ligero, altamente atenuada, de color dorado y fermentacion baja, que exhibe una excelente retencion de espuma y un elegante aroma a lupulo floral. Chispeante, limpia y refrescante, una Pilsner que exhibe la mas fina calidad de malta y lupulo Alemán.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SESSION IPA",
    detail: 
    "4.3% - IBU 31  |    Cerveza clara de color amarillento. Cuerpo lígero, con sabores a malta y caramelo, aunque el predominante principal es el lúpulo. Amargor medio alto. Notas a resina, frutas tropicales y cítricas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "SCOTTISH EXPORT",
    detail: "5.51% - IBU 18 |   Cerveza maltosa, con notas acarameladas y algo de butterscotch. De color cobrizo, con espuma blanquecina y cremosa. Sabor a migas de pan tostado, bizcochos y galletas. Amargor bajo y cuerpo medio, carbonatación moderada.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "BELGIAN DUBBEL",
    detail: "7.48%  - IBU 22.9 |  Cerveza rubia de un color dorado profundo. Maltas caramelo y clara presencia de miel en sabor y aroma. El cuerpo es de ligero a medio, buena tomabilidad. Amargor bajo y balance hacia la malta y la miel.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "POKER BOURBON",
    detail: "8.53%  - IBU 51  |   Cerveza de color ámbar profundo acompañado por una espuma densa de gran retención. Cuerpo medio alto. Sabor a maltas caramelo y fuerte carácter a alcohol! y amargor acompañados por un sutil ahumado. El agregado de bourbon Jack Daniel's en madurado da notas a madera y vainilla hacia el final.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "PORTER",
    detail: "5.7% - IBU 26.6 |    Cerveza oscura profunda con un rojo intenso a trasluz. Caracter tostado y notas a chocolate. Sabores a malta, bizcochos y pan tostado. Cuerpo medio alto, amargor medio con notas terrosas.",
    price: "700",
    section: "LATAS",
  },
  {
    name: "TIRADA",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "PORRÓN",
    detail: "",
    price: "700",
    section: "HEINEKEN",
  },
  {
    name: "FERNET BRANCA",
    detail: "",
    price: "900",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "MINT TONIC",
    detail: "Branca menta + Tónica",
    price: "800",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA +NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "SERNOVA + SPEED",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "APEROL SPRITZ",
    detail: "",
    price: "1000",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "PRPEE WHISKY",
    detail: "Whisky Jameson, manzana macerada, almíbar y dash de limon",
    price: "110",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + NARANJA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "CAMPARI + TONICA",
    detail: "",
    price: "850",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "NEGRONI",
    detail: "",
    price: "1100",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "HOLDMOSER + SPEED",
    detail: "",
    price: "1500",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "JAGGER + SPEED",
    detail: "",
    price: "1700",
    section: "TRAGOS CLASICOS",
  },
  {
    name: "BEEFEATER",
    detail: "",
    price: "1200",
    section: "ONLY GIN",
  },
  {
    name: "BOMBAY",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "BULL DOG",
    detail: "",
    price: "1500",
    section: "ONLY GIN",
  },
  {
    name: "MERLE",
    detail: "",
    price: "1000",
    section: "ONLY GIN",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMON & CLAVO DE OLOR",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "NARANJA & ENEBRO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "POMELO & ANIS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "LIMA & MENTA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "LIMA & MENTA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIMIENTA Y PIEL DE POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PIER DE NARANJA Y CANELA EN RAMA",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "PEPINO Y ROMERO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "PEPINO Y ROMERO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ROMERO Y POMELO",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ROMERO Y POMELO",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ENEBRO Y PIEL DE LIMON",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
  ,
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "portela",
    price: "1000",
    section: "GIN + BOTANICO",
  },
  {
    name: "ANIS ESTRELLADO Y ARÁNDANOS",
    detail: "beffeater",
    price: "1300",
    section: "GIN + BOTANICO",
  },
 
  {
    name: "TIRADO",
    detail: "",
    price: "800",
    section: "PORTELA",
  },
  {
    name: "PALERMO TONIC",
    detail: "gin tirado, lima, pomelo, jugo de limón, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "BERRIES TONIC",
    detail: "gin tirado, lima, frutos rojos, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "RECOLETA TONIC",
    detail: "gin tirado, lima, maracuya, almíbar y tónica",
    price: "1000",
    section: "BAIRES",
  },
  {
    name: "JULEP TONIC",
    detail: "refrescante julep de gin con jugo de pomelo",
    price: "1100",
    section: "BAIRES",
  },
  {
    name: "TOM COLLINS",
    detail: "gin tirado, almíbar, jugo de limón y soda",
    price: "",
    section: "BAIRES",
  },
  {
    name: "BERRIES",
    detail: "sernova - frutos rojos - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PASSION FRUIT",
    detail: "sernova - maracuya - dash almíbar - jugo de naranja",
    price: "1000",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PEACH",
    detail: "sernova - durazno natural - soda - almíbar - jugo de limón",
    price: "900",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "PUNCH ESTACION",
    detail: "ron dorado - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "PUNCH MALIBU",
    detail: "ron malibu - frutas de estación - almibar - jugo de naranja - jugo de pomelo",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "MAITE",
    detail: "ron blanco - ron malibu - anana macerado - jugo naranja",
    price: "1100",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO TRADICIONAL",
    detail: "ron blanco - menta - limón - almibar - soda",
    price: "900",
    section: "COKTELEÍA",
  },
  {
    name: "MOJITO MARACUYA",
    detail: "ron blanco - maracuya - menta - limón - azúcar - soda",
    price: "950",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRISIMA",
    detail: "Ron blanco- lima - azúcar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIRINHA",
    detail: "Cachaza, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPIROSKA",
    detail: "Vodka, lima y azucar. Eleccion frutos rojos o maracuya.",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "BOOM",
    detail: "shaken de ron blanco con lima y azúcar",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI FRUTOS ROJOS",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI MARACUYA",
    detail: "",
    price: "1000",
    section: "COKTELEÍA",
  },
  {
    name: "CAIPI DURAZNO",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGER JULEP",
    detail: "jagger - menta - azúcar negra - dash limón - jugo de naranja o pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "JAGGERBULL",
    detail: "jagger + red bull",
    price: "1800",
    section: "COKTELEÍA",
  },
  {
    name: "APPLELIME JAGGER",
    detail: "jagger - manzana - lima macerados - jugo de manzana",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA BREZZE",
    detail: "absolut vainilla - arándanos - jugo de pomelo",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT MANDARIN REBEL",
    detail: "absolut mandarina - coca cola - rodaja de naranja",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT P.S",
    detail: "absolut pears - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT VAINILLA COLA",
    detail: "absolut vainilla - sprite - limón",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT APEACH TONIC",
    detail: "absolut apeach - tónica - lima",
    price: "1300",
    section: "COKTELEÍA",
  },
  ,
  {
    name: "ABSOLUT MANGO MOJITO",
    detail: "absolut mango - menta - limón - azúcar - soda",
    price: "1300",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + SPEED",
    detail: "",
    price: "1600",
    section: "COKTELEÍA",
  },
  {
    name: "ABSOLUT + RED BULL",
    detail: "",
    price: "",
    section: "COKTELEÍA",
  },
  {
    name: "COCA~COLA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SPRITE",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "FANTA",
    detail: "lata",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "SCHWEPPES POMELO",
    detail: "500cc",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA CON GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AGUA SIN GAS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "AQUARIUS",
    detail: "",
    price: "400",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA CLASICA",
    detail: "menta - limón - azúcar - agua",
    price: "500",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE MARACUYA",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA DE FRUTOS ROJOS",
    detail: "",
    price: "600",
    section: "SIN ALCOHOL",
  },
  {
    name: "LIMONADA SHAKEN",
    detail: "shaken de jugo de naranja, pulpa de maracuya, almibar y jugo de naranja",
    price: "650",
    section: "COKTELEÍA",
  },
  {
    name: "MIX DE CITRICOS CON FRUTOS ROJOS",
    detail: "",
    price: "700",
    section: "COKTELEÍA",
  },
  {
    name: "BARON B EXTRA BRUT",
    detail: "750cc",
    price: "6500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON BRUT NATURE",
    detail: "750cc",
    price: "4500",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },
  {
    name: "CHANDON",
    detail: "750cc",
    price: "4000",
    section: "ESPUMANTES",
  },



  // ---------------Food
  {
    name: "CHICKEN FINGERS",
    detail: "bastoncitos de pollo con salsa picante ",
    price: "1600",
    section: "TAPEOS",
  },
  {
    name: "CHEESE SNACKS",
    detail: "bastoncitos de muzzarella con salsa alioli",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADAS VEGANAS",
    detail: "4 empanadas de verduras salteadas, zanahoria, morron, cebolla, berenjenas y champigniones",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADAS DE CARNE",
    detail: "4 empanadas de carne, cebolla y queso con salsa picante",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "EMPANADS DE POLLO",
    detail: "4 empanadas de pollo con salsa alioli",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "RABAS",
    detail: "rabas con limon y dip salsa alioli",
    price: "2500",
    section: "TAPEOS",
  },
  {
    name: "TORTILLA",
    detail: "tortilla con jamón, queso, verdeo y lactonesa de ajo",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "TIRTUKKA VEGGIE",
    detail: "tortilla con roquefort, nuez, verdeo y lactonesa de ajo",
    price: "1400",
    section: "TAPEOS",
  },
  {
    name: "BAIRES",
    detail: "papas bañadas con cheddar, acompañadas de panceta y verdeo",
    price: "1400",
    section: "PAPAS",
  },
  {
    name: "PALERMO",
    detail: "papas con salchichas, huevo frito y barbacoa",
    price: "1500",
    section: "PAPAS",
  },
  {
    name: "PUERTO MADERO",
    detail: "papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1600",
    section: "PAPAS",
  },
  {
    name: "CONGRESO",
    detail: "papas con bondiola desmenuzada, salsa de queso fundido y pimientos asados",
    price: "1700",
    section: "PAPAS",
  },
  {
    name: "LOMO ACOMPAÑADO DE PAPAS ESPAÑOLAS",
    detail: "lom con papas españolas verduras asadas, con manteca de hirbas. dip de criolla con chimichurri",
    price: "2100",
    section: "PRINCIPALES",
  },
  {
    name: "BONDIOLA ACOMPAÑADA DE PAPAS ESPAÑOLAS",
    detail: "bondiola braseada cubierta de queso fundido, lonjas de panceta, huevos fritos, cebolla caramelizada y pimientos asados acompañadas de papas españolas",
    price: "2100",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA MADERO",
    detail: "milanesa con fondeau de queso y mix de hongos",
    price: "1900",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA NAPO",
    detail: "milanesa,salsa de tomate, jamon, queso y oregano - acompañada con papas españolas",
    price: "1700",
    section: "PRINCIPALES",
  },
  {
    name: "MILANESA A CABALLO",
    detail: "milanesa con queso cheddar y huevo frito acomáñada con papas fritas",
    price: "1800",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE LOMO",
    detail: "fideos de arroz, verduras salteadas, lomo, panceta, hongos, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE VERDURA",
    detail: "fideos de arroz, verduras salteadas, almendras tostadas, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "WOK DE POLLO",
    detail: "fideos de arroz, verduras salteadas, pollo, almendras, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "PRINCIPALES",
  },
  {
    name: "CESAR",
    detail: "mix de hojas verdes, péchuga grille, croutons, queso parmesano y sressing caesar",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "CAPRESSE",
    detail: "cubos de queso, cherrys confitados, aceitunas negras y pesto de almbahaca",
    price: "1700",
    section: "ENSALADAS",
  },
  {
    name: "MEDITERRANEA",
    detail: "mix de hojas verdes, jamon serrano, cheese sticks, tomates cherry, aceite de oliva",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "CRISPY",
    detail: "mix de hojas verdes, pollo crispy, crocantes de panceta, queso en hebras y dressing ranch",
    price: "1800",
    section: "ENSALADAS",
  },
  {
    name: "BAIRES",
    detail: "pan de papa, medallon de carne, panceta y doble cheddar",
    price: "1500",
    section: "ENTRE PANES",
  },
  {
    name: "CONGRESO",
    detail: "pan de papa, doble carne, doble cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "DOBLE BAIRES",
    detail: "pan de papa, doble carne, doble cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1750",
    section: "ENTRE PANES",
  },
  {
    name: "PALERMO",
    detail: "pan de papa, triple carne, triple cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "1750",
    section: "ENTRE PANES",
  },
  {
    name: "MEGA BAIRES",
    detail: "pan de papa. triple carne, triple cheddar, panceta, cebolla caramelizada y huevo frito",
    price: "",
    section: "ENTRE PANES",
  },
  {
    name: "MILA",
    detail: "mila en pan arabe, jamon, queso, lechuga y tomate",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "LOMO BAIRES",
    detail: "lomo en pan arabe, doble cheddar, panceta y huevo frito",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "LOMO MADERO",
    detail: "lomo en pan arabe, doble cheddar, palta, tomate y huevo",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "VEGGIE",
    detail: "medallon de espinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano y ciboulette",
    price: "1600",
    section: "ENTRE PANES",
  },
  {
    name: "BONDIOLA MADERO",
    detail: "bondiola desmenuzada con salsa criolla, queso tibo, palta, tomate y huevo",
    price: "1800",
    section: "ENTRE PANES",
  },
  {
    name: "CLÁSICA",
    detail: "muzzarella y jamon",
    price: "1300",
    section: "PIZZAS",
  },
  {
    name: "NAPOLITANA",
    detail: "muzzarella, albahaca y aceite de oliva",
    price: "1550",
    section: "PIZZAS",
  },
  {
    name: "ESPECIAL",
    detail: "muzzarella, jamon, morrones y aceitunas",
    price: "1650",
    section: "PIZZAS",
  },
  {
    name: "SERRANA",
    detail: "muzzarella, jamon crudo y rucula",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "AMERICANA",
    detail: "muzzarella, panceta y huevo frito",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "4 QUESOS",
    detail: "",
    price: "1750",
    section: "PIZZAS",
  },
  {
    name: "BAIRES",
    detail: "muzzarella, cheddar, pollo, barbacoa casera y verdeo",
    price: "1800",
    section: "PIZZAS",
  },
  {
    name: "PIZZA INDIVIDUAL",
    detail: "",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "PANINI",
    detail: "jamón y queso",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "PAPAS",
    detail: "papas con cheddar, panceta y verdeo",
    price: "1200",
    section: "SIN T.A.C.C",
  },
  {
    name: "EMPANADAS VEGANAS",
    detail: "3 empanadas de verduras salteadas, zanahoria, morron, cebolla, berenjena y champignoines",
    price: "1400",
    section: "VEGGIE",
  },
  {
    name: "PAPAS PUERTO MADERO",
    detail: "papas con salsa de queso fundido, mix de hongos y nuez",
    price: "1600",
    section: "VEGGIE",
  },
  {
    name: "WOK DE VERDURAS",
    detail: "fideos de arroz, verduras salteadas, almendras tostadas, salsa de soja y semillas de sesamo",
    price: "1600",
    section: "VEGGIE",
  },
  {
    name: "BURGUER VEGGIE",
    detail: "medallon de espinaca/calabaza con lechuga, palta, cebolla caramelizada, queso crema, lonjas de parmesano y ciboulette",
    price: "1600",
    section: "VEGGIE",
  },

  // ---------------Wines
  {
    name: "CANILLA 1",
    detail: "malbec reserva (mendoza)",
    price: "350",
    section: "VINO TIRADO",
  },
  {
    name: "CANILLA 2",
    detail: "malbec premium (mendoza)",
    price: "400",
    section: "VINO TIRADO",
  },
  {
    name: "CANILLA 3",
    detail: "cabernet franc premium (mendoza)",
    price: "400",
    section: "VINO TIRADO",
  },
  {
    name: "CANILLA 4",
    detail: "blend de malbec/malbec de diferentes alturas (mendoza)",
    price: "350",
    section: "VINO TIRADO",
  },
  {
    name: "NUBE NEGRA",
    detail: "",
    price: "3500",
    section: "MALBEC",
  },
  {
    name: "TERRAZAS DE LOS ANDES APELACIÓN DE ORIGEN",
    detail: "",
    price: "2500",
    section: "MALBEC",
  },
  {
    name: "GRAN VINO CHAÑARMUYO",
    detail: "",
    price: "1800",
    section: "MALBEC",
  },
  {
    name: "EDUARDO VIDAL ",
    detail: "el espía cap.1",
    price: "1800",
    section: "MALBEC",
  },
  {
    name: "MALABARISTA",
    detail: "",
    price: "1500",
    section: "MALBEC",
  },
  {
    name: "CAUTIVADOR",
    detail: "",
    price: "1500",
    section: "MALBEC",
  },
  {
    name: "TUCUMEN RESERVA",
    detail: "",
    price: "1400",
    section: "MALBEC",
  },
  {
    name: "TESTA MATTA",
    detail: "",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "EDUARDO VIDAL",
    detail: "cayado",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "GUASON",
    detail: "",
    price: "1200",
    section: "MALBEC",
  },
  {
    name: "TERRAZAS DE LOS ANDES RESERVA",
    detail: "",
    price: "1200",
    section: "CABERNET SAUVIGNON",
  },
  {
    name: "GRAN VINO CHAÑARMUYO FRANC",
    detail: "",
    price: "1800",
    section: "CABERNET FRANC",
  },
  {
    name: "GUASON FRANC",
    detail: "",
    price: "1200",
    section: "CABERNET FRANC",
  },
  {
    name: "DON BICHO REVERA WINES",
    detail: "",
    price: "2500",
    section: "ORGÁNICOS",
  },
  {
    name: "GRAN VINO CHAÑARMUYO TANAT",
    detail: "",
    price: "1800",
    section: "TANAT",
  },
  {
    name: "MALABARISTA COFERMENTADO N1",
    detail: "",
    price: "1900",
    section: "BLEND/CO-FERMENTADOS/BI-VARIETALES",
  },
  {
    name: "MALABARISTA COFERMENTADO N2",
    detail: "",
    price: "1900",
    section: "BLEND/CO-FERMENTADOS/BI-VARIETALES",
  },
  {
    name: "TURBIO CRUZA DE BLANCAS",
    detail: "clasico",
    price: "1900",
    section: "VINO BLANCO",
  },
  {
    name: "MALABARISTA ESPUMANTE DULCE",
    detail: "",
    price: "1300",
    section: "VINO BLANCO",
  },

  {
    name: "FINCA GABRIEL DULCE",
    detail: "",
    price: "1200",
    section: "VINO BLANCO",
  },

  {
    name: "GUASON ESPUMANTE DULCE",
    detail: "",
    price: "1200",
    section: "VINO BLANCO",
  },
  {
    name: "SIEMPRE TENGO UN PLAN B",
    detail: "torrontes dulce",
    price: "1600",
    section: "VINO BLANCO",
  },
  {
    name: "TERRAZAS DE LOS ANDES RESERVA ROSE DE MALBECS",
    detail: "",
    price: "1600",
    section: "VINO ROSADO",
  },
  {
    name: "FINCA GABRIEL ROSE DULCE",
    detail: "",
    price: "1200",
    section: "VINO ROSADO",
  }
  
]
// ----------------------------FIN---------